services:
  - type: web
    name: abu-aneefah-academy
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: APP_NAME
        value: "Abu Aneefah Islamic Academy"
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        value: "base64:Ac9YMVK/ASVFvjRI8BDUlUzxEkAgu2IxOV1cOS+2n1E="
      - key: DB_CONNECTION
        value: pgsql
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: FILESYSTEM_DISK
        value: local
